# Generated by Django 4.2.5 on 2023-10-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comedian',
            name='profile_picture',
            field=models.ImageField(default='gigglproject/pics/defaultcomedian.jpeg', upload_to='comedian_pics/'),
            preserve_default=False,
        ),
    ]
