# Generated by Django 4.2.5 on 2023-10-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedians', '0002_comedian_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comedian',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='comedian_pics/'),
        ),
    ]
