# Generated by Django 4.2.5 on 2023-10-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedians', '0003_alter_comedian_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comedian',
            name='profile_picture',
            field=models.TextField(default='https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png'),
            preserve_default=False,
        ),
    ]
