# Generated by Django 4.2.5 on 2023-10-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
