# Generated by Django 4.2.5 on 2023-10-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_podcast_youtube_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
